### ISSUE TITLE
Sleep Problem Lenovo IP330s 14IKB

### ISSUE THREAD

**Issue by armadeas** [kasti0/Hackintosh_Lenovo-IdeaPad-330s-15ikb#1]
I have problems when in big sur sleep it can't work properly.
Previously in Catalina Sleep went well, but in Big Sur when I locked the screen, the screen would turn off and then turn on but the display was blank.
I have to connect the laptop to an external monitor so that the display on the laptop appears, only then can I remove the external monitor.

![image](https://user-images.githubusercontent.com/6720930/101994460-3217b280-3cf5-11eb-89d6-c23b8d63c11d.png)

[https://www.youtube.com/watch?v=eWEy7I4ls8I](url)

[https://www.youtube.com/watch?v=HSe4MKUnj-M](url)

**Comment by kasti0** [comment]
Different Type of laptop.
At least provide your config.plist and make sure all kext and OC are up to date

**Comment by kasti0** [comment]
add "igfxonln=1" to boot arguments
