### ISSUE TITLE
BIOS edits

### ISSUE THREAD

**Issue by dreamwhite** [kasti0/Hackintosh_Lenovo-IdeaPad-330s-15ikb#2]
Thank you so much for your repository. It's really useful especially for the BIOS edits. May I ask you if you could provide the offset for the CFG Lock? I can't manage to extract the BIOS offset :'( 

I'm helping a user with the same model of your laptop and can't manage to get the CFG Lock offset, even with ControlMsrE2.efi :'( 

Thank you so much

**Comment by kasti0** [comment]
No, I won't provide any offset as they heavily depend on your exact machine and bios version. If I give you mine and it's different to your actual offset it could break your laptop.
The thing is, on mine there wasn't even a CFG lock. The option was there in BIOS but it didn't matter if it was enabled or not. Maybe it's the same for your laptop. Just disable the respective quirks in your OC config.plist and try if you can still boot.

**Comment by dreamwhite** [comment]
> No, I won't provide any offset as they heavily depend on your exact machine and bios version. If I give you mine and it's different to your actual offset it could break your laptop.
> The thing is, on mine there wasn't even a CFG lock. The option was there in BIOS but it didn't matter if it was enabled or not. Maybe it's the same for your laptop. Just disable the respective quirks in your OC config.plist and try if you can still boot.

Thank you so much for your reply ^^
Using VerifyMsrE2.efi says that MSR 0xE2 is LOCKED so I don't think that disabling the respective quirks in OC config.plist will do the job. In any case I'll try and let you know if it boots.

Also, may I ask you what's your current BIOS version? As far as I know, if the laptop and the BIOS version is the same of yours, the offset should be the same. Am I wrong? 

Thank you so much for your effort btw ^^

**Comment by kasti0** [comment]
The VerifyMsr2 Tool also reported the lock for me and also reported the lock as unlocked after I changed the value in the BIOS. But that didn't seem to have any effect, I was still able to boot with the quirks disabled.

The offset should be the same, but without you being able to check it before actually trying to apply it we can't say that for sure.
