### ISSUE TITLE
an internet connection is required to install macos

### ISSUE THREAD

**Issue by visheshind** [kasti0/Hackintosh_Lenovo-IdeaPad-330s-15ikb#6]
he is asking for the internet connection but i already connected the ethernet cable 
i have a exact same pc as yours.

**Comment by kasti0** [comment]
this model doesn't have any ethernet port.

**Comment by visheshind** [comment]
in my laptop i have one , so i inserted intel-mausi .kext file
but the internet still not working

**Comment by kasti0** [comment]
>  i have a exact same pc as yours.

this seems to be incorrect then. 
I won't give you support for different hardware here. please refer to the r/Hackintosh subreddit or the Discord server.

**Comment by visheshind** [comment]
what if you have an ethernet port on your system , then what will you use ,intel mausi or other
